In [2]:
import pandas as pd
from urllib.parse import quote_plus
import sqlalchemy
from pathlib import Path
from typing import Dict, Any
import yaml

In [ ]:
app_user_accounts = pd.read_csv('data/raw/app_user_accounts.csv')
app_user_profiles = pd.read_csv('data/raw/app_user_profiles.csv')
application_error_logs = pd.read_csv('data/raw/application_error_logs.csv')
auth_login_events = pd.read_csv('data/raw/auth_login_events.csv')
auth_session_tokens = pd.read_csv('data/raw/auth_session_tokens.csv')
billing_invoices = pd.read_csv('data/raw/billing_invoices.csv')
clickstream_events = pd.read_csv('data/raw/clickstream_events.csv')
experiment_assignments = pd.read_csv('data/raw/experiment_assignments.csv')
feature_flag_exposures = pd.read_csv('data/raw/feature_flag_exposures.csv')
frontend_performance_events = pd.read_csv('data/raw/frontend_performance_events.csv')
mobile_application_events = pd.read_csv('data/raw/mobile_application_events.csv')
notification_delivery_events = pd.read_csv('data/raw/notification_delivery_events.csv')
payment_transactions = pd.read_csv('data/raw/payment_transactions.csv')
product_sessions = pd.read_csv('data/raw/product_sessions.csv')
subscription_accounts = pd.read_csv('data/raw/subscription_accounts.csv')
subscription_state_history = pd.read_csv('data/raw/subscription_state_history.csv')
support_ticket_events = pd.read_csv('data/raw/support_ticket_events.csv')
support_tickets = pd.read_csv('data/raw/support_tickets.csv')
user_feedback_submissions = pd.read_csv('data/raw/user_feedback_submissions.csv')
user_device_profiles = pd.read_csv('data/raw/user_device_profiles.csv')
user_master_profiles = pd.read_csv('data/raw/user_master_profiles.csv')

In [19]:
app_user_accounts.head()

,user_account_id,external_user_uuid,email_address,email_normalized,email_verified_at,password_hash,password_algorithm,account_status_enum,registration_source,locale_code,timezone_name,marketing_opt_in_flag,gdpr_consent_version,last_successful_login_at,created_at,updated_at,deleted_at,row_version_id,is_deleted
0,1501,841958e2-a8d9-4a56-b31e-41df67908070,mia.white@icloud.com,mia.white@icloud.com,2025-05-23 19:13:53+00:00,$2a$12$R9h/cIPz0gi.URNNX3rubedAK0ReQxc/ZG3.cQ....,bcrypt,ACTIVE,WEB,en-AU,Australia/Sydney,False,v3.0,2025-06-01 11:06:38+00:00,2025-05-23 13:35:39+00:00,2025-06-01 11:06:38+00:00,NaN,13,False
1,1502,425f6a60-4eb6-4944-92b2-8a6f7d91e798,caleb.lavoie9@hotmail.com,caleb.lavoie9@hotmail.com,2025-10-19 20:11:00+00:00,$2a$12$R9h/cIPz0gi.URNNX3rubedAK0ReQxc/ZG3.cQ....,bcrypt,ACTIVE,IOS,en-CA,America/Toronto,False,v3.0,2025-10-21 09:10:12+00:00,2025-10-17 23:03:54+00:00,2025-10-21 09:10:12+00:00,NaN,13,False
2,1503,1a11bd8d-d0fd-44f4-911b-05faf6b54c5a,gaspard.leroy@gmail.com,gaspard.leroy@gmail.com,2026-03-20 02:34:32+00:00,$2a$12$R9h/cIPz0gi.URNNX3rubedAK0ReQxc/ZG3.cQ....,bcrypt,ACTIVE,IOS,fr-FR,Europe/Paris,False,v3.0,2026-04-02 21:21:16+00:00,2026-03-18 09:43:34+00:00,2026-04-02 21:21:16+00:00,NaN,8,False
3,1504,51683211-c053-40d3-816d-aae7c4f93440,henry.wilson@icloud.com,henry.wilson@icloud.com,2024-10-04 00:26:42+00:00,$2a$12$R9h/cIPz0gi.URNNX3rubedAK0ReQxc/ZG3.cQ....,bcrypt,ACTIVE,WEB,en-AU,Australia/Sydney,False,v3.0,2024-10-08 20:22:48+00:00,2024-10-02 14:45:07+00:00,2024-10-08 20:22:48+00:00,NaN,1,False
4,1505,cc9b8c5e-c014-4405-a433-c34397e86a50,murilo.santos93@outlook.com.br,murilo.santos93@outlook.com.br,2024-02-16 07:39:07+00:00,$2a$12$R9h/cIPz0gi.URNNX3rubedAK0ReQxc/ZG3.cQ....,bcrypt,ACTIVE,ANDROID,pt-BR,America/Sao_Paulo,True,v3.0,2024-03-02 10:19:46+00:00,2024-02-14 11:06:34+00:00,2024-03-02 10:19:46+00:00,NaN,6,False

In [20]:
app_user_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_account_id           500 non-null    int64
 1   external_user_uuid        500 non-null    object
 2   email_address             500 non-null    object
 3   email_normalized          500 non-null    object
 4   email_verified_at         500 non-null    object
 5   password_hash             500 non-null    object
 6   password_algorithm        500 non-null    object
 7   account_status_enum       500 non-null    object
 8   registration_source       500 non-null    object
 9   locale_code               500 non-null    object
 10  timezone_name             500 non-null    object
 11  marketing_opt_in_flag     500 non-null    bool
 12  gdpr_consent_version      500 non-null    object
 13  last_successful_login_at  500 non-null    object
 14  created_at                500 non-null    object
 15  updated_at                500 non-null    object
 16  deleted_at                8 non-null      object
 17  row_version_id            500 non-null    int64
 18  is_deleted                500 non-null    bool
dtypes: bool(2), int64(2), object(15)
memory usage: 67.5+ KB

In [4]:
app_user_accounts.drop(columns='primary_workspace_id', inplace=True)
app_user_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_account_id           10000 non-null  int64
 1   external_user_uuid        10000 non-null  object
 2   email_address             10000 non-null  object
 3   email_normalized          10000 non-null  object
 4   email_verified_at         10000 non-null  object
 5   password_hash             10000 non-null  object
 6   password_algorithm        10000 non-null  object
 7   account_status_enum       10000 non-null  object
 8   registration_source       10000 non-null  object
 9   locale_code               10000 non-null  object
 10  timezone_name             10000 non-null  object
 11  marketing_opt_in_flag     10000 non-null  bool
 12  gdpr_consent_version      10000 non-null  object
 13  last_successful_login_at  10000 non-null  object
 14  created_at                10000 non-null  object
 15  updated_at                10000 non-null  object
 16  deleted_at                188 non-null    object
 17  row_version_id            10000 non-null  int64
 18  is_deleted                10000 non-null  bool
dtypes: bool(2), int64(2), object(15)
memory usage: 1.3+ MB

In [5]:
app_user_profiles.head()

,profile_id,user_account_id,first_name,last_name,display_name,company_name,job_title,industry_code,employee_count_range,annual_revenue_range,phone_number,country_code,profile_attributes_json,created_at,updated_at
0,1,1,Damien,Gonzales,Damien G.,सैनी PLC,Oficial de justiça,TECH,11-50,<1M,NaN,GB,"{""theme"": ""dark"", ""onboarding_completed"": true}",2026-04-05 22:57:32+00:00,2026-04-05 22:57:32+00:00
1,2,2,Manuella,伊藤,Manuella 伊.,Steckel Klingelhöfer GbR,Sales promotion account executive,RETAIL,1000+,1M-10M,NaN,GB,"{""theme"": ""dark"", ""onboarding_completed"": true}",2025-07-03 17:53:58+00:00,2025-07-03 17:53:58+00:00
2,3,3,Albrecht,岡本,Albrecht 岡.,कपूर Group,Environmental health practitioner,TECH,201-1000,1M-10M,090-9582-8190,US,"{""theme"": ""dark"", ""onboarding_completed"": true}",2025-05-22 19:20:31+00:00,2025-05-22 19:20:31+00:00
3,4,4,Kieran,Wang,Kieran W.,Gorlitz,Chartered accountant,HEALTHCARE,51-200,1M-10M,NaN,US,"{""theme"": ""dark"", ""onboarding_completed"": true}",2024-10-18 02:06:11+00:00,2024-10-18 02:06:11+00:00
4,5,5,Gregory,खत्री,Gregory ख.,Reinhardt,Mathematiker,TECH,201-1000,<1M,0116 496 0179,DE,"{""theme"": ""dark"", ""onboarding_completed"": true}",2024-10-26 20:05:24+00:00,2024-10-26 20:05:24+00:00

In [6]:
app_user_profiles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   profile_id               10000 non-null  int64
 1   user_account_id          10000 non-null  int64
 2   first_name               10000 non-null  object
 3   last_name                10000 non-null  object
 4   display_name             10000 non-null  object
 5   company_name             10000 non-null  object
 6   job_title                10000 non-null  object
 7   industry_code            10000 non-null  object
 8   employee_count_range     10000 non-null  object
 9   annual_revenue_range     10000 non-null  object
 10  phone_number             5030 non-null   object
 11  country_code             10000 non-null  object
 12  profile_attributes_json  10000 non-null  object
 13  created_at               10000 non-null  object
 14  updated_at               10000 non-null  object
dtypes: int64(2), object(13)
memory usage: 1.1+ MB

In [7]:
app_user_profiles.fillna({'country_code':'Unknown'}, inplace=True)
app_user_profiles.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   profile_id               10000 non-null  int64
 1   user_account_id          10000 non-null  int64
 2   first_name               10000 non-null  object
 3   last_name                10000 non-null  object
 4   display_name             10000 non-null  object
 5   company_name             10000 non-null  object
 6   job_title                10000 non-null  object
 7   industry_code            10000 non-null  object
 8   employee_count_range     10000 non-null  object
 9   annual_revenue_range     10000 non-null  object
 10  phone_number             5030 non-null   object
 11  country_code             10000 non-null  object
 12  profile_attributes_json  10000 non-null  object
 13  created_at               10000 non-null  object
 14  updated_at               10000 non-null  object
dtypes: int64(2), object(13)
memory usage: 1.1+ MB

In [8]:
application_error_logs.head()

,error_log_id,service_name,service_version,environment_name,trace_id,span_id,exception_class,error_message,stack_trace,http_status_code,endpoint_path,raw_error_payload,occurred_at
0,400001,api-gateway-service,v2.1.0,PROD,2cd79b83b35d415d867132f416d8ed80,844943a9db5146ec,GatewayTimeoutException,HTTP 504: The upstream microservice failed to ...,at com.enterprise.engine.GatewayFilter.lambda$...,504,/v2/analytics/compute-aggregates,"{""timeout_threshold_ms"": 5000}",2026-05-18 19:54:48
1,400002,api-gateway-service,v2.1.0,PROD,9913c7d2a3804756b993753c89bde8c1,f3c836a96e004174,DatabaseDeadlockException,HTTP 504: The upstream microservice failed to ...,at com.enterprise.engine.GatewayFilter.lambda$...,504,/v2/analytics/compute-aggregates,"{""timeout_threshold_ms"": 5000}",2026-07-07 00:00:00
2,400003,api-gateway-service,v2.1.0,PROD,7fa9eede1c2648f1a787f9116b81b267,eb50957235024377,GatewayTimeoutException,HTTP 504: The upstream microservice failed to ...,at com.enterprise.engine.GatewayFilter.lambda$...,504,/v2/analytics/compute-aggregates,"{""timeout_threshold_ms"": 5000}",2026-07-07 00:00:00
3,400004,api-gateway-service,v2.1.0,PROD,f118190127854d5998dadab591ae5877,7efbd758e4ab436d,GatewayTimeoutException,HTTP 504: The upstream microservice failed to ...,at com.enterprise.engine.GatewayFilter.lambda$...,504,/v2/analytics/compute-aggregates,"{""timeout_threshold_ms"": 5000}",2026-07-07 00:00:00
4,400005,api-gateway-service,v2.1.0,PROD,51b2218678454948828e8cd050853ff4,b15b4535748545fa,GatewayTimeoutException,HTTP 504: The upstream microservice failed to ...,at com.enterprise.engine.GatewayFilter.lambda$...,504,/v2/analytics/compute-aggregates,"{""timeout_threshold_ms"": 5000}",2026-07-07 00:00:00

In [9]:
application_error_logs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 658 entries, 0 to 657
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   error_log_id       658 non-null    int64
 1   service_name       658 non-null    object
 2   service_version    658 non-null    object
 3   environment_name   658 non-null    object
 4   trace_id           658 non-null    object
 5   span_id            658 non-null    object
 6   exception_class    658 non-null    object
 7   error_message      658 non-null    object
 8   stack_trace        658 non-null    object
 9   http_status_code   658 non-null    int64
 10  endpoint_path      658 non-null    object
 11  raw_error_payload  658 non-null    object
 12  occurred_at        658 non-null    object
dtypes: int64(2), object(11)
memory usage: 67.0+ KB

In [10]:
auth_login_events.head()

,login_event_id,user_account_id,login_method,authentication_result,client_ip_address,user_agent_string,device_fingerprint_hash,geo_country,risk_score_raw,created_at,failure_reason_code
0,1,1,PASSWORD,SUCCESS,32.23.84.230,Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like...,49ce50349381496899bebc87ecf9189d,US,0.022831,2026-07-07 00:00:00,NaN
1,2,1,PASSWORD,SUCCESS,151.49.138.140,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7),3a4b72ad0dfd4b438695c16ba7bc0487,UK,0.215207,2026-06-22 22:57:32,NaN
2,3,1,SSO,SUCCESS,114.221.243.253,Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like...,31ed2a86e8af4f698e817b2bdbe5a45d,US,0.234662,2026-07-07 00:00:00,NaN
3,4,1,SSO,SUCCESS,30.246.214.3,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7),fccc7bfe199a4d99adbc160658c5cfa1,US,0.030788,2026-07-07 00:00:00,NaN
4,5,1,PASSWORD,SUCCESS,60.225.23.42,Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like...,ae1e9a4003d34790a9e20985e0f3fc12,UK,0.046136,2026-07-07 00:00:00,NaN

In [11]:
auth_login_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 149964 entries, 0 to 149963
Data columns (total 11 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   login_event_id           149964 non-null  int64
 1   user_account_id          149964 non-null  int64
 2   login_method             149964 non-null  object
 3   authentication_result    149964 non-null  object
 4   client_ip_address        149964 non-null  object
 5   user_agent_string        149964 non-null  object
 6   device_fingerprint_hash  149964 non-null  object
 7   geo_country              149964 non-null  object
 8   risk_score_raw           149964 non-null  float64
 9   created_at               149964 non-null  object
 10  failure_reason_code      17994 non-null   object
dtypes: float64(1), int64(2), object(8)
memory usage: 12.6+ MB

In [12]:
auth_session_tokens.head()

,session_id,user_account_id,access_token_hash,refresh_token_hash,device_id,client_ip_address,user_agent_string,session_started_at,session_expires_at,session_terminated_at,termination_reason,created_at
0,38efbaa6-462a-4cda-9e05-a9680c31724c,1,5e51a843e7d54ac19b3d773cc247decc,646ac0a0d8254c5887536d55af364761,49ce50349381496899bebc87ecf9189d,32.23.84.230,Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like...,2026-07-07 00:00:00,2026-07-07 12:18:44,2026-07-07 11:50:40,TIMEOUT,2026-07-07 00:00:00
1,73e13e18-9af4-4943-8f8c-84dfdb8a5d12,1,8e1667a92f9e444fac1678ff228651c9,238492de2d9f485aa84a8f7757c58c34,3a4b72ad0dfd4b438695c16ba7bc0487,151.49.138.140,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7),2026-06-22 22:57:32,2026-06-23 10:38:32,2026-06-23 10:14:53,TIMEOUT,2026-06-22 22:57:32
2,885176da-b646-4a2a-af75-b8b2764baa2c,1,e334e789226d4ba293b3000d8c1251b8,76c6bad23a764f23ae2f34a60b6a3abf,31ed2a86e8af4f698e817b2bdbe5a45d,114.221.243.253,Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like...,2026-07-07 00:00:00,2026-07-07 21:13:12,2026-07-07 20:53:28,USER_LOGOUT,2026-07-07 00:00:00
3,c84e3b41-dc15-41d0-8bda-b7a99a55b686,1,382b6546c4034240846506d36bdeeadb,d9e9d6179c7c4a01b51a68d48147c0a6,fccc7bfe199a4d99adbc160658c5cfa1,30.246.214.3,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7),2026-07-07 00:00:00,2026-07-07 23:15:24,2026-07-07 22:54:17,USER_LOGOUT,2026-07-07 00:00:00
4,953a924f-eeef-4e44-b74d-7a5b69e8377a,1,7b968c2e50144709ac115290ccd3a504,fe17648f27e047c3b2ef1ee6852d0eb8,ae1e9a4003d34790a9e20985e0f3fc12,60.225.23.42,Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like...,2026-07-07 00:00:00,2026-07-07 17:05:58,2026-07-07 16:55:42,USER_LOGOUT,2026-07-07 00:00:00

In [13]:
auth_session_tokens.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131970 entries, 0 to 131969
Data columns (total 12 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   session_id             131970 non-null  object
 1   user_account_id        131970 non-null  int64
 2   access_token_hash      131970 non-null  object
 3   refresh_token_hash     131970 non-null  object
 4   device_id              131970 non-null  object
 5   client_ip_address      131970 non-null  object
 6   user_agent_string      131970 non-null  object
 7   session_started_at     131970 non-null  object
 8   session_expires_at     131970 non-null  object
 9   session_terminated_at  131970 non-null  object
 10  termination_reason     131970 non-null  object
 11  created_at             131970 non-null  object
dtypes: int64(1), object(11)
memory usage: 12.1+ MB

In [14]:
billing_invoices.head()

,subscription_id,due_date,subtotal_amount,tax_amount,discount_amount,total_amount,invoice_id,external_invoice_id,invoice_status,currency_code,paid_at,created_at
0,10001,2026-04-20 01:55:57,299.90,23.99,0.0,323.89,100001,inv_73ff8e8177af4e,PAID,USD,2026-04-20 09:55:57,2026-04-19 01:55:57
1,10001,2026-05-20 01:55:57,299.90,23.99,0.0,323.89,100002,inv_c1e7d6af4ce34d,PAID,USD,2026-05-20 11:55:57,2026-05-19 01:55:57
2,10001,2026-06-19 01:55:57,299.90,23.99,0.0,323.89,100003,inv_fe29b21daddb4b,PAID,USD,2026-06-19 22:55:57,2026-06-18 01:55:57
3,10003,2025-06-06 06:20:03,29.99,2.40,0.0,32.39,100004,inv_b111923a81a641,PAID,USD,2025-06-07 02:20:03,2025-06-05 06:20:03
4,10003,2025-07-06 06:20:03,29.99,2.40,0.0,32.39,100005,inv_19c7a975da3448,FAILED,USD,NaN,2025-07-05 06:20:03

In [15]:
billing_invoices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93139 entries, 0 to 93138
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   subscription_id      93139 non-null  int64
 1   due_date             93139 non-null  object
 2   subtotal_amount      93139 non-null  float64
 3   tax_amount           93139 non-null  float64
 4   discount_amount      93139 non-null  float64
 5   total_amount         93139 non-null  float64
 6   invoice_id           93139 non-null  int64
 7   external_invoice_id  93139 non-null  object
 8   invoice_status       93139 non-null  object
 9   currency_code        93139 non-null  object
 10  paid_at              92532 non-null  object
 11  created_at           93139 non-null  object
dtypes: float64(4), int64(2), object(6)
memory usage: 8.5+ MB

In [16]:
clickstream_events.head()

,event_id,product_session_id,event_uuid,event_name,event_category,page_screen_name,ui_component_name,interaction_type,event_timestamp,ingestion_timestamp,event_sequence_number,latency_ms,client_ip_address,geo_country,geo_city,sdk_version,event_payload_json,created_at
0,9000001,38efbaa6-462a-4cda-9e05-a9680c31724c,a0aeb1bd-84b3-45f2-9186-d48748356597,view_dashboard,user_action,Dashboard,MAIN_WINDOW,click,2026-07-07 00:00:25,2026-07-07 00:00:25.108,1,417.648789,127.0.0.1,US,San Francisco,web-sdk-v4.12.0,"{""element_id"": ""core_grid_v1""}",2026-07-07 00:00:25
1,9000002,38efbaa6-462a-4cda-9e05-a9680c31724c,ed475567-cf69-44cc-ae31-0784ad5f88d3,view_dashboard,user_action,Reports,EXPORT_BUTTON,click,2026-07-07 00:00:36,2026-07-07 00:00:36.230,2,494.648789,127.0.0.1,US,San Francisco,web-sdk-v4.12.0,"{""element_id"": ""core_grid_v1""}",2026-07-07 00:00:36
2,9000003,38efbaa6-462a-4cda-9e05-a9680c31724c,97805a3f-14de-4c4e-881e-631cb47e3066,view_dashboard,user_action,BillingSettings,NAV_BAR,click,2026-07-07 00:01:30,2026-07-07 00:01:30.130,3,455.648789,127.0.0.1,US,San Francisco,web-sdk-v4.12.0,"{""element_id"": ""core_grid_v1""}",2026-07-07 00:01:30
3,9000004,73e13e18-9af4-4943-8f8c-84dfdb8a5d12,6bf78b9b-095f-466c-8bd1-bb829cf30fe4,submit_form,user_action,BillingSettings,NAV_BAR,click,2026-06-22 22:57:57,2026-06-22 22:57:57.297,1,264.080128,127.0.0.1,US,San Francisco,web-sdk-v4.12.0,"{""element_id"": ""core_grid_v1""}",2026-06-22 22:57:57
4,9000005,73e13e18-9af4-4943-8f8c-84dfdb8a5d12,e55b326a-a5df-4564-ab5a-f3dff5634405,submit_form,user_action,Dashboard,SAVE_CTA,click,2026-06-22 22:58:22,2026-06-22 22:58:22.242,2,217.080128,127.0.0.1,US,San Francisco,web-sdk-v4.12.0,"{""element_id"": ""core_grid_v1""}",2026-06-22 22:58:22

In [17]:
clickstream_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 593285 entries, 0 to 593284
Data columns (total 18 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   event_id               593285 non-null  int64
 1   product_session_id     593285 non-null  object
 2   event_uuid             593285 non-null  object
 3   event_name             593285 non-null  object
 4   event_category         593285 non-null  object
 5   page_screen_name       593285 non-null  object
 6   ui_component_name      593285 non-null  object
 7   interaction_type       593285 non-null  object
 8   event_timestamp        593285 non-null  object
 9   ingestion_timestamp    593285 non-null  object
 10  event_sequence_number  593285 non-null  int64
 11  latency_ms             593285 non-null  float64
 12  client_ip_address      593285 non-null  object
 13  geo_country            593285 non-null  object
 14  geo_city               593285 non-null  object
 15  sdk_version            593285 non-null  object
 16  event_payload_json     593285 non-null  object
 17  created_at             593285 non-null  object
dtypes: float64(1), int64(2), object(15)
memory usage: 81.5+ MB

In [18]:
clickstream_events.isnull().sum()

event_id                 0
product_session_id       0
event_uuid               0
event_name               0
event_category           0
page_screen_name         0
ui_component_name        0
interaction_type         0
event_timestamp          0
ingestion_timestamp      0
event_sequence_number    0
latency_ms               0
client_ip_address        0
geo_country              0
geo_city                 0
sdk_version              0
event_payload_json       0
created_at               0
dtype: int64

In [19]:
experiment_assignments.head()

,assignment_id,user_account_id,experiment_key,treatment_group,assignment_hash,allocation_algorithm,assigned_at
0,1400001,1,EXP_CHECKOUT_FLOW_REDESIGN_2024,VARIANT_A,5431f32151114cae,murmur3_salted_hash,2026-04-05 23:07:32+00:00
1,1400002,2,EXP_CHECKOUT_FLOW_REDESIGN_2024,CONTROL,e4222ef5e7394047,murmur3_salted_hash,2025-07-03 18:03:58+00:00
2,1400003,3,EXP_CHECKOUT_FLOW_REDESIGN_2024,CONTROL,407510391ef84764,murmur3_salted_hash,2025-05-22 19:30:31+00:00
3,1400004,4,EXP_CHECKOUT_FLOW_REDESIGN_2024,VARIANT_B,eae2909739334f45,murmur3_salted_hash,2024-10-18 02:16:11+00:00
4,1400005,5,EXP_CHECKOUT_FLOW_REDESIGN_2024,VARIANT_A,80ae7febf43e4a63,murmur3_salted_hash,2024-10-26 20:15:24+00:00

In [20]:
experiment_assignments.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 7 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   assignment_id         10000 non-null  int64
 1   user_account_id       10000 non-null  int64
 2   experiment_key        10000 non-null  object
 3   treatment_group       10000 non-null  object
 4   assignment_hash       10000 non-null  object
 5   allocation_algorithm  10000 non-null  object
 6   assigned_at           10000 non-null  object
dtypes: int64(2), object(5)
memory usage: 547.0+ KB

In [21]:
feature_flag_exposures.head()

,exposure_id,user_account_id,feature_flag_key,variant_key,evaluation_reason,rule_set_version,exposure_context_json,exposed_at
0,1300001,1,pdf-generation-v2,control,RULE_MATCH,v1.0.4,"{""user_tier"": ""premium""}",2026-04-06 02:57:32+00:00
1,1300002,1,advanced-search-elastic,control,RULE_MATCH,v1.0.4,"{""user_tier"": ""premium""}",2026-04-06 02:57:32+00:00
2,1300003,2,pdf-generation-v2,treatment,RULE_MATCH,v1.0.4,"{""user_tier"": ""premium""}",2025-07-03 21:53:58+00:00
3,1300004,2,advanced-search-elastic,treatment,RULE_MATCH,v1.0.4,"{""user_tier"": ""premium""}",2025-07-03 21:53:58+00:00
4,1300005,3,pdf-generation-v2,control,RULE_MATCH,v1.0.4,"{""user_tier"": ""premium""}",2025-05-22 23:20:31+00:00

In [22]:
feature_flag_exposures.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 8 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   exposure_id            20000 non-null  int64
 1   user_account_id        20000 non-null  int64
 2   feature_flag_key       20000 non-null  object
 3   variant_key            20000 non-null  object
 4   evaluation_reason      20000 non-null  object
 5   rule_set_version       20000 non-null  object
 6   exposure_context_json  20000 non-null  object
 7   exposed_at             20000 non-null  object
dtypes: int64(2), object(6)
memory usage: 1.2+ MB

In [23]:
frontend_performance_events.head()

,performance_event_id,product_session_id,page_route,first_contentful_paint_ms,largest_contentful_paint_ms,cumulative_layout_shift,time_to_interactive_ms,dom_load_time_ms,api_wait_time_ms,render_time_ms,network_type,captured_at
0,200001,38efbaa6-462a-4cda-9e05-a9680c31724c,/dashboard/home,872,1372,0.144746,1490,1072,464,277,WIFI,2026-07-07 00:00:00
1,200002,73e13e18-9af4-4943-8f8c-84dfdb8a5d12,/settings/billing,928,1196,0.079494,1634,1128,231,236,4G,2026-06-22 22:57:32
2,200003,885176da-b646-4a2a-af75-b8b2764baa2c,/settings/billing,762,1121,0.119704,1408,962,106,548,WIFI,2026-07-07 00:00:00
3,200004,c84e3b41-dc15-41d0-8bda-b7a99a55b686,/dashboard/home,393,608,0.127831,932,593,102,270,4G,2026-07-07 00:00:00
4,200005,953a924f-eeef-4e44-b74d-7a5b69e8377a,/dashboard/home,801,1217,0.271603,1421,1001,209,116,ETHERNET,2026-07-07 00:00:00

In [24]:
frontend_performance_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131970 entries, 0 to 131969
Data columns (total 12 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   performance_event_id         131970 non-null  int64
 1   product_session_id           131970 non-null  object
 2   page_route                   131970 non-null  object
 3   first_contentful_paint_ms    131970 non-null  int64
 4   largest_contentful_paint_ms  131970 non-null  int64
 5   cumulative_layout_shift      131970 non-null  float64
 6   time_to_interactive_ms       131970 non-null  int64
 7   dom_load_time_ms             131970 non-null  int64
 8   api_wait_time_ms             131970 non-null  int64
 9   render_time_ms               131970 non-null  int64
 10  network_type                 131970 non-null  object
 11  captured_at                  131970 non-null  object
dtypes: float64(1), int64(7), object(4)
memory usage: 12.1+ MB

In [25]:
mobile_application_events.head()

,user_account_id,application_event,occurred_at,mobile_event_id,device_id,app_version,os_version,push_token,event_payload
0,8,INSTALL,2025-01-15 19:00:46+00:00,1200001,502222010b8647d290a14cd8490eeec9,v3.5.0,Android 14,tok_e412b3a7536a41e585df,"{""network_carrier"": ""Verizon""}"
1,12,INSTALL,2025-12-13 17:15:50+00:00,1200002,904bda7b324b4d7caffb6fc22b8b55e8,v3.5.0,Android 14,tok_f9b33bff921645c2bf8b,"{""network_carrier"": ""Verizon""}"
2,17,INSTALL,2025-02-25 06:35:48+00:00,1200003,9d14d675089b4e2e9cd003605a799ce2,v3.5.0,iOS 17.4,tok_2cbeb6ccc2a14d348c9d,"{""network_carrier"": ""Verizon""}"
3,18,INSTALL,2025-03-15 15:42:01+00:00,1200004,9d9b3e1bcc3746d0b9e7f040487f3280,v3.5.0,iOS 17.4,tok_0fd7720b56a145618133,"{""network_carrier"": ""Verizon""}"
4,19,INSTALL,2024-12-19 14:38:32+00:00,1200005,8587132ca164411e80dc32d28b0a5615,v3.5.0,iOS 17.4,tok_110017c42f9948448f82,"{""network_carrier"": ""Verizon""}"

In [26]:
mobile_application_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7738 entries, 0 to 7737
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_account_id    7738 non-null   int64
 1   application_event  7738 non-null   object
 2   occurred_at        7738 non-null   object
 3   mobile_event_id    7738 non-null   int64
 4   device_id          7738 non-null   object
 5   app_version        7738 non-null   object
 6   os_version         7738 non-null   object
 7   push_token         7738 non-null   object
 8   event_payload      7738 non-null   object
dtypes: int64(2), object(7)
memory usage: 544.2+ KB

In [27]:
notification_delivery_events.head()

,notification_event_id,user_account_id,notification_channel,template_id,provider_name,provider_message_id,delivery_status,provider_response,created_at
0,800001,1,PUSH,PRODUCT_UPDATE,PNS_GATEWAY,msg_e0abd2ab934948,OPENED,"{""smtp_status_code"": 250, ""gateway_latency_ms""...",2026-06-17 22:57:32+00:00
1,800002,1,EMAIL,PRODUCT_UPDATE,SENDGRID,msg_dad76be8c9c64e,FAILED,"{""smtp_status_code"": 250, ""gateway_latency_ms""...",2026-06-03 22:57:32+00:00
2,800003,1,EMAIL,WELCOME_PROMO,TWILIO,msg_dde050d432e643,OPENED,"{""smtp_status_code"": 250, ""gateway_latency_ms""...",2026-05-04 22:57:32+00:00
3,800004,2,EMAIL,PRODUCT_UPDATE,PNS_GATEWAY,msg_b221144e62bb43,OPENED,"{""smtp_status_code"": 250, ""gateway_latency_ms""...",2026-04-12 17:53:58+00:00
4,800005,2,PUSH,WELCOME_PROMO,SENDGRID,msg_7441caa0de634d,OPENED,"{""smtp_status_code"": 250, ""gateway_latency_ms""...",2025-10-20 17:53:58+00:00

In [28]:
notification_delivery_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50147 entries, 0 to 50146
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   notification_event_id  50147 non-null  int64
 1   user_account_id        50147 non-null  int64
 2   notification_channel   50147 non-null  object
 3   template_id            50147 non-null  object
 4   provider_name          50147 non-null  object
 5   provider_message_id    50147 non-null  object
 6   delivery_status        50147 non-null  object
 7   provider_response      50147 non-null  object
 8   created_at             50147 non-null  object
dtypes: int64(2), object(7)
memory usage: 3.4+ MB

In [29]:
payment_transactions.head()

,payment_transaction_id,invoice_id,external_payment_id,payment_provider,payment_method_type,transaction_status,failure_code,failure_message,processor_response_code,amount,currency_code,provider_response_payload,initiated_at,completed_at
0,500001,100001,ch_b83e08aae31343,BRAINTREE,CARD,SUCCESS,NaN,NaN,approved,323.89,USD,"{""network_status"": ""approved_by_network""}",2026-04-19 01:55:57,2026-04-20 09:55:57
1,500002,100002,ch_1424b1373d0a49,ADYEN,CARD,SUCCESS,NaN,NaN,approved,323.89,USD,"{""network_status"": ""approved_by_network""}",2026-05-19 01:55:57,2026-05-20 11:55:57
2,500003,100003,ch_517ad1aab1eb4a,STRIPE,CARD,SUCCESS,NaN,NaN,approved,323.89,USD,"{""network_status"": ""approved_by_network""}",2026-06-18 01:55:57,2026-06-19 22:55:57
3,500004,100004,ch_27a3f22c54ef48,ADYEN,CARD,SUCCESS,NaN,NaN,approved,32.39,USD,"{""network_status"": ""approved_by_network""}",2025-06-05 06:20:03,2025-06-07 02:20:03
4,500005,100005,ch_15847f7607ab45,ADYEN,ACH,FAILED,card_declined,Your card has insufficient funds.,insufficient_funds,32.39,USD,"{""network_status"": ""approved_by_network""}",2025-07-05 06:20:03,2025-07-06 18:20:03

In [30]:
payment_transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93139 entries, 0 to 93138
Data columns (total 14 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   payment_transaction_id     93139 non-null  int64
 1   invoice_id                 93139 non-null  int64
 2   external_payment_id        93139 non-null  object
 3   payment_provider           93139 non-null  object
 4   payment_method_type        93139 non-null  object
 5   transaction_status         93139 non-null  object
 6   failure_code               607 non-null    object
 7   failure_message            607 non-null    object
 8   processor_response_code    93139 non-null  object
 9   amount                     93139 non-null  float64
 10  currency_code              93139 non-null  object
 11  provider_response_payload  93139 non-null  object
 12  initiated_at               93139 non-null  object
 13  completed_at               93139 non-null  object
dtypes: float64(1), int64(2), object(11)
memory usage: 9.9+ MB

In [31]:
product_sessions.head()

,product_session_id,user_account_id,anonymous_device_id,platform_type,app_version,operating_system,device_model,browser_name,browser_version,session_started_at,session_ended_at,termination_reason,created_at
0,38efbaa6-462a-4cda-9e05-a9680c31724c,1,49ce50349381496899bebc87ecf9189d,WEB,v3.5.0,Android 14,MacBook Pro,Chrome,122.0.0,2026-07-07 00:00:00,2026-07-07 11:50:40,TIMEOUT,2026-07-07 00:00:00
1,73e13e18-9af4-4943-8f8c-84dfdb8a5d12,1,3a4b72ad0dfd4b438695c16ba7bc0487,ANDROID,v3.5.0,macOS 14.2,MacBook Pro,Chrome,122.0.0,2026-06-22 22:57:32,2026-06-23 10:14:53,TIMEOUT,2026-06-22 22:57:32
2,885176da-b646-4a2a-af75-b8b2764baa2c,1,31ed2a86e8af4f698e817b2bdbe5a45d,WEB,v3.4.2,Android 14,iPhone 15,Chrome,122.0.0,2026-07-07 00:00:00,2026-07-07 20:53:28,USER_LOGOUT,2026-07-07 00:00:00
3,c84e3b41-dc15-41d0-8bda-b7a99a55b686,1,fccc7bfe199a4d99adbc160658c5cfa1,ANDROID,v3.4.1,iOS 17,Galaxy S24,Safari,122.0.0,2026-07-07 00:00:00,2026-07-07 22:54:17,USER_LOGOUT,2026-07-07 00:00:00
4,953a924f-eeef-4e44-b74d-7a5b69e8377a,1,ae1e9a4003d34790a9e20985e0f3fc12,IOS,v3.4.2,iOS 17,iPhone 15,Chrome,122.0.0,2026-07-07 00:00:00,2026-07-07 16:55:42,USER_LOGOUT,2026-07-07 00:00:00

In [32]:
product_sessions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 131970 entries, 0 to 131969
Data columns (total 13 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   product_session_id   131970 non-null  object
 1   user_account_id      131970 non-null  int64
 2   anonymous_device_id  131970 non-null  object
 3   platform_type        131970 non-null  object
 4   app_version          131970 non-null  object
 5   operating_system     131970 non-null  object
 6   device_model         131970 non-null  object
 7   browser_name         131970 non-null  object
 8   browser_version      131970 non-null  object
 9   session_started_at   131970 non-null  object
 10  session_ended_at     131970 non-null  object
 11  termination_reason   131970 non-null  object
 12  created_at           131970 non-null  object
dtypes: int64(1), object(12)
memory usage: 13.1+ MB

In [33]:
subscription_accounts.head()

,subscription_id,user_account_id,external_billing_customer_id,subscription_plan_code,subscription_status,billing_cycle,trial_started_at,trial_ends_at,subscription_started_at,subscription_ended_at,auto_renew_enabled,cancellation_requested_at,cancellation_reason_code,cancellation_comment,created_at,updated_at
0,10001,1,cus_23a9b4c1e4ac4c,TEAM_YEARLY,ACTIVE,MONTHLY,2026-04-06 01:55:57,2026-04-20 01:55:57,2026-04-20 01:55:57,NaN,True,NaN,NaN,NaN,2026-04-06 01:55:57,2026-04-20 01:55:57
1,10002,2,cus_e983c7df162d42,PRO_MONTHLY,TRIAL,MONTHLY,2025-07-04 05:36:02,2025-07-18 05:36:02,2025-07-18 05:36:02,NaN,True,NaN,NaN,NaN,2025-07-04 05:36:02,2025-07-18 05:36:02
2,10003,3,cus_5f63f184a1c64a,PRO_MONTHLY,CANCELLED,MONTHLY,2025-05-23 06:20:03,2025-06-06 06:20:03,2025-06-06 06:20:03,2025-07-24 01:24:31,False,2025-07-23 21:21:25,TOO_EXPENSIVE,NaN,2025-05-23 06:20:03,2025-06-06 06:20:03
3,10004,5,cus_35728139243444,PRO_MONTHLY,ACTIVE,YEARLY,2024-10-26 21:21:53,2024-11-09 21:21:53,2024-11-09 21:21:53,NaN,True,NaN,NaN,NaN,2024-10-26 21:21:53,2024-11-09 21:21:53
4,10005,6,cus_0818cd49c25c45,PRO_MONTHLY,CANCELLED,MONTHLY,2026-03-29 15:59:37,2026-04-12 15:59:37,2026-04-12 15:59:37,2026-07-07 00:00:00,False,2026-07-06 14:41:44,POOR_PERFORMANCE,NaN,2026-03-29 15:59:37,2026-04-12 15:59:37

In [34]:
subscription_accounts.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9160 entries, 0 to 9159
Data columns (total 16 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   subscription_id               9160 non-null   int64
 1   user_account_id               9160 non-null   int64
 2   external_billing_customer_id  9160 non-null   object
 3   subscription_plan_code        9160 non-null   object
 4   subscription_status           9160 non-null   object
 5   billing_cycle                 9160 non-null   object
 6   trial_started_at              9160 non-null   object
 7   trial_ends_at                 9160 non-null   object
 8   subscription_started_at       9160 non-null   object
 9   subscription_ended_at         1956 non-null   object
 10  auto_renew_enabled            9160 non-null   bool
 11  cancellation_requested_at     1956 non-null   object
 12  cancellation_reason_code      1956 non-null   object
 13  cancellation_comment          0 non-null      float64
 14  created_at                    9160 non-null   object
 15  updated_at                    9160 non-null   object
dtypes: bool(1), float64(1), int64(2), object(12)
memory usage: 1.1+ MB

In [35]:
subscription_state_history.head()

,subscription_state_id,subscription_id,previous_state,new_state,transition_trigger,actor_user_id,raw_transition_payload,effective_at,created_at
0,1,10001,INITIAL,TRIAL,USER_ACTION,1,"{""source"": ""web_checkout""}",2026-04-06 01:55:57,2026-04-06 01:55:57
1,2,10001,TRIAL,ACTIVE,PAYMENT_SUCCESS,-1,"{""processor"": ""stripe"", ""auto_bill"": true}",2026-04-20 01:55:57,2026-04-20 01:55:57
2,3,10002,INITIAL,TRIAL,USER_ACTION,2,"{""source"": ""web_checkout""}",2025-07-04 05:36:02,2025-07-04 05:36:02
3,4,10003,INITIAL,TRIAL,USER_ACTION,3,"{""source"": ""web_checkout""}",2025-05-23 06:20:03,2025-05-23 06:20:03
4,5,10003,TRIAL,ACTIVE,PAYMENT_SUCCESS,-1,"{""processor"": ""stripe"", ""auto_bill"": true}",2025-06-06 06:20:03,2025-06-06 06:20:03

In [36]:
subscription_state_history.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19791 entries, 0 to 19790
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   subscription_state_id   19791 non-null  int64
 1   subscription_id         19791 non-null  int64
 2   previous_state          19791 non-null  object
 3   new_state               19791 non-null  object
 4   transition_trigger      19791 non-null  object
 5   actor_user_id           19791 non-null  int64
 6   raw_transition_payload  19791 non-null  object
 7   effective_at            19791 non-null  object
 8   created_at              19791 non-null  object
dtypes: int64(3), object(6)
memory usage: 1.4+ MB

In [37]:
support_ticket_events.head()

,ticket_event_id,ticket_id,event_type,actor_type,actor_id,event_payload,created_at
0,700001,300001,INITIAL_ASSIGNMENT,BOT,-99,"{""routing_tier"": ""L2_TECHNICAL_SUPPORT""}",2025-11-05 17:53:58+00:00
1,700002,300001,AGENT_COMMENT,AGENT,101,"{""routing_tier"": ""L2_TECHNICAL_SUPPORT""}",2025-11-05 18:45:58+00:00
2,700003,300002,INITIAL_ASSIGNMENT,BOT,-99,"{""routing_tier"": ""L2_TECHNICAL_SUPPORT""}",2026-06-20 22:18:38+00:00
3,700004,300002,AGENT_COMMENT,AGENT,104,"{""routing_tier"": ""L2_TECHNICAL_SUPPORT""}",2026-06-20 23:16:38+00:00
4,700005,300003,INITIAL_ASSIGNMENT,BOT,-99,"{""routing_tier"": ""L2_TECHNICAL_SUPPORT""}",2026-03-29 22:18:38+00:00

In [38]:
support_ticket_events.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9632 entries, 0 to 9631
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ticket_event_id  9632 non-null   int64
 1   ticket_id        9632 non-null   int64
 2   event_type       9632 non-null   object
 3   actor_type       9632 non-null   object
 4   actor_id         9632 non-null   int64
 5   event_payload    9632 non-null   object
 6   created_at       9632 non-null   object
dtypes: int64(3), object(4)
memory usage: 526.9+ KB

In [39]:
support_tickets.head()

,ticket_id,user_account_id,external_ticket_id,ticket_status,ticket_priority,category_code,subcategory_code,subject,description,assigned_agent_id,first_response_at,resolved_at,created_at
0,300001,2,zd_61861b5097fe,CLOSED,MEDIUM,GENERAL_INQUIRY,GENERAL_ISSUE,System error during workflow operation,The application throws an unhandled state erro...,101,2025-11-05 18:37:58+00:00,2025-11-08 10:37:58+00:00,2025-11-05 17:53:58+00:00
1,300002,6,zd_f9a5a22aa7f7,OPEN,URGENT,GENERAL_INQUIRY,GENERAL_ISSUE,System error during workflow operation,The application throws an unhandled state erro...,104,2026-06-20 23:37:38+00:00,NaN,2026-06-20 22:18:38+00:00
2,300003,6,zd_fe90e0cd60db,OPEN,HIGH,UI_BUG,COMPONENT_CRASH,System error during workflow operation,The application throws an unhandled state erro...,121,2026-03-29 23:30:38+00:00,NaN,2026-03-29 22:18:38+00:00
3,300004,6,zd_622237d2a232,CLOSED,URGENT,UI_BUG,COMPONENT_CRASH,System error during workflow operation,The application throws an unhandled state erro...,113,2026-05-20 01:31:38+00:00,2026-05-22 06:31:38+00:00,2026-05-19 22:18:38+00:00
4,300005,6,zd_1d48e508b3cb,CLOSED,URGENT,UI_BUG,COMPONENT_CRASH,System error during workflow operation,The application throws an unhandled state erro...,114,2026-04-20 00:27:38+00:00,2026-04-21 06:27:38+00:00,2026-04-19 22:18:38+00:00

In [40]:
support_tickets.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4816 entries, 0 to 4815
Data columns (total 13 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ticket_id           4816 non-null   int64
 1   user_account_id     4816 non-null   int64
 2   external_ticket_id  4816 non-null   object
 3   ticket_status       4816 non-null   object
 4   ticket_priority     4816 non-null   object
 5   category_code       4816 non-null   object
 6   subcategory_code    4816 non-null   object
 7   subject             4816 non-null   object
 8   description         4816 non-null   object
 9   assigned_agent_id   4816 non-null   int64
 10  first_response_at   4816 non-null   object
 11  resolved_at         3077 non-null   object
 12  created_at          4816 non-null   object
dtypes: int64(3), object(10)
memory usage: 489.3+ KB

In [41]:
user_feedback_submissions.head()

,feedback_id,user_account_id,feedback_type,rating_value,free_text_feedback,source_screen,session_id,metadata_json,submitted_at
0,1500001,1208,NPS,9,"Great platform, really speeds up our team oper...",DASHBOARD_HOME,c43e8a83-def8-4977-b774-ac4b2ec9c5f6,"{""sdk_environment"": ""PROD""}",2026-04-21 08:49:48+00:00
1,1500002,1097,NPS,10,"Great platform, really speeds up our team oper...",DASHBOARD_HOME,b13a5bfd-6428-413e-b18b-74709bd0851a,"{""sdk_environment"": ""PROD""}",2025-12-18 15:02:51+00:00
2,1500003,7036,NPS,9,"Great platform, really speeds up our team oper...",DASHBOARD_HOME,6b8dccfe-9691-4804-bc1d-790b619b3dc2,"{""sdk_environment"": ""PROD""}",2024-09-27 03:45:13+00:00
3,1500004,3091,NPS,8,"Great platform, really speeds up our team oper...",SETTINGS_BILLING,6123a970-3b3f-4aba-bf76-144c1ce4d3d4,"{""sdk_environment"": ""PROD""}",2024-07-18 04:55:27+00:00
4,1500005,9928,NPS,9,"Great platform, really speeds up our team oper...",SETTINGS_BILLING,49090f6b-d2fc-493f-bc0f-0a574bd9b93a,"{""sdk_environment"": ""PROD""}",2025-05-11 05:42:43+00:00

In [42]:
user_feedback_submissions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   feedback_id         2000 non-null   int64
 1   user_account_id     2000 non-null   int64
 2   feedback_type       2000 non-null   object
 3   rating_value        2000 non-null   int64
 4   free_text_feedback  2000 non-null   object
 5   source_screen       2000 non-null   object
 6   session_id          2000 non-null   object
 7   metadata_json       2000 non-null   object
 8   submitted_at        2000 non-null   object
dtypes: int64(3), object(6)
memory usage: 140.8+ KB

In [ ]:
dfs = {
    "app_user_accounts":app_user_accounts, 
       "app_user_profiles":app_user_profiles,
       "application_error_logs":application_error_logs,
       "auth_login_events":auth_login_events,
       "auth_session_tokens":auth_session_tokens,
       "billing_invoices":billing_invoices,
       "clickstream_events":clickstream_events,
       "experiment_assignments":experiment_assignments,
       "feature_flag_exposures":feature_flag_exposures,
       "frontend_performance_events":frontend_performance_events,
       "mobile_application_events":mobile_application_events,
       "notification_delivery_events":notification_delivery_events,
       "payment_transactions":payment_transactions,
       "product_sessions":product_sessions,
       "subscription_accounts":subscription_accounts,
       "subscription_state_history":subscription_state_history,
       "support_ticket_events":support_ticket_events,
       "support_tickets":support_tickets,
       "user_feedback_submissions":user_feedback_submissions,
       "user_device_profiles": user_device_profiles,
       "user_master_profiles": user_master_profiles}

In [10]:
for name, df in dfs.items():
    print(name, ': ', df.duplicated().sum())

app_user_accounts :  0
app_user_profiles :  0
application_error_logs :  0
auth_login_events :  0
auth_session_tokens :  0
billing_invoices :  0
clickstream_events :  0
experiment_assignments :  0
feature_flag_exposures :  0
frontend_performance_events :  0
mobile_application_events :  0
notification_delivery_events :  0
payment_transactions :  0
product_sessions :  0
subscription_accounts :  0
subscription_state_history :  0
support_ticket_events :  0
support_tickets :  0
user_feedback_submissions :  0

In [3]:
BASE_DIR = Path().cwd().parents[0]
YAML_PATH = BASE_DIR / "config.yaml"

def _load_yaml() -> Dict[str, Any]:
    if not YAML_PATH.exists():
        return {}
    with open(YAML_PATH, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    return data

In [ ]:
cnfg_yaml = _load_yaml()
cnfg = cnfg_yaml['database']
username = cnfg['username']
password = quote_plus(cnfg['password'])
host = cnfg['host']
port = cnfg['port']
database = cnfg['database']  

engine = sqlalchemy.create_engine(
    f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}"
)
# Specify your target schema name here
target_schema = "stg"

# Create the schema if it does not exist
with engine.begin() as connection:
    connection.execute(sqlalchemy.text(f"CREATE SCHEMA IF NOT EXISTS {target_schema};"))
    print(f"📁 Schema '{target_schema}' verified/created.")

# Upload DataFrames
for name, df in dfs.items():
    df.head().to_sql(
        name=f"{name}", 
        con=engine, 
        schema=target_schema, 
        index=False,
        if_exists="replace",
        
    )
    print(f"✅ Successfully uploaded {name} to schema '{target_schema}'!")

📁 Schema 'stg' verified/created.
✅ Successfully uploaded user_master_profiles to schema 'stg'!

In [4]:
with engine.begin() as connection:
    for name, df in dfs.items():
    
        connection.execute(sqlalchemy.text(f"TRUNCATE TABLE {target_schema}.{name};"))
        print(f"{name} Table truncated.")

user_master_profiles Table truncated.